# Generated by Django 5.0.14 on 2026-10-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_attendanceentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
