# Generated by Django 5.0.14 on 2026-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_studentprofile_last_bonus_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=20)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_preview', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Gemini')], max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
