# Generated by Django 5.0.14 on 2026-10-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
